before_script:
    - git clone https://github.com/sstephenson/bats.git /tmp/bats
    - mkdir -p /tmp/local
    - bash /tmp/bats/install.sh /tmp/local
    - export PATH=$PATH:/tmp/local/bin
    - git clone -b travis https://github.com/cirulls/xspec.git /tmp/xspec
    - export SAXON_CP=/tmp/xspec/saxon9he.jar

script:
    - echo "execute bats unit tests"
    - cd test && bats xspec.bats

script:
    - echo "execute XSpec unit tests"
    - cd test && ./run-xspec-tests.sh
    # - /tmp/xspec/bin/xspec.sh /tmp/xspec/test/xspec-variable.xspec &> result.log && if grep -q ".*failed:\s[1-9]" result.log; then exit 1; fi
